controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    type: FollowJointTrajectory
    default: True
    joints:
      - kinova_arm_joint_1
      - kinova_arm_joint_2
      - kinova_arm_joint_3
      - kinova_arm_joint_4
      - kinova_arm_joint_5
      - kinova_arm_joint_6
  - name: gripper_controller
    action_ns: gripper_action
    type: GripperCommand
    default: True
    joints:
      - kinova_arm_right_finger_bottom_joint